### ISSUE TITLE
Charge percentage bar view suggestion

### ISSUE THREAD

**Issue by inspirit** [jverkoey/ElectricSidecar#37]
A small suggestion to only fill the charge bar to actual percentage in similar fashion to watch battery complication:
![WhatsApp Image 2023-01-19 at 12 09 33](https://user-images.githubusercontent.com/223020/213427769-5037ba24-6ef6-4ad9-8b89-300cd1680442.jpeg)

**Comment by leearmstrong** [comment]
On the flip side I have apps that do the same...

![incoming-641885B7-326B-4F4F-811E-CDD280D91F8D](https://user-images.githubusercontent.com/82891/213440719-177f4cef-2d73-48a4-8a6d-79bda23cabc5.PNG)

**Comment by inspirit** [comment]
ohh didn't see this coming :)

**Comment by jverkoey** [comment]
I don't have a strong preference on this one. Maybe we can make it configurable?

**Comment by jverkoey** [comment]
Upcoming release candidate will include a unified gauge style:

![Simulator Screen Shot - Apple Watch Series 8 (45mm) - 2023-01-22 at 22 53 02](https://user-images.githubusercontent.com/45670/213981165-beec8fd8-9ed8-4eab-8b03-3e0fcb648b1d.png)

![Simulator Screen Shot - Apple Watch Series 8 (45mm) - 2023-01-22 at 22 53 11](https://user-images.githubusercontent.com/45670/213981184-4df1e3a1-377d-4cec-8067-3594921ff3f0.png)
