### ISSUE TITLE
Ver 1.1(4) complication not updating, phone app doesnt allow to log in

### ISSUE THREAD

**Issue by inspirit** [jverkoey/ElectricSidecar#39]
Hi! Latest update introduced few issues:
1. watch complication is not updating (alway default state), if open the app it shows correct info inside
2. phone app does not allow to log in, it says open watch for automatic log in but when watch app is opened nothing happens, and there is no way to manually input log in data because email/pass fields are disabled.

**Comment by jverkoey** [comment]
Try doing the following:

1. Delete the app from your phone and watch.
2. Restart both devices.
3. Reinstall the app.
4. Log in on your watch.
5. Open the watch app and the iPhone app; the watch icon should go from crossed out to showing a connected icon.
6. Log in on your phone.

**Comment by inspirit** [comment]
I did that following your instructions in version release notes. however it does not solve the issues :( 
the watch icon in the iphone app changes to indicate that i opened watch app but it still does not log in on the phone and i stay on that screen forever.

**Comment by jverkoey** [comment]
Ah I see one area where it might have a bug.

**Comment by jverkoey** [comment]
Build 6 has some authentication stability improvements. Let me know if that fixes it for you!

**Comment by inspirit** [comment]
yup it fixed the issue, i could not log in automatically opening app on watch but i could input my credentials and it worked.
also complication is updating on watch now.

**Comment by jverkoey** [comment]
Amazing!
