### ISSUE TITLE
complication misalignment 

### ISSUE THREAD

**Issue by inspirit** [jverkoey/ElectricSidecar#41]
Hi! after latest update there is slight misalignment in complication percentage label:
![WhatsApp Image 2023-02-06 at 09 42 11](https://user-images.githubusercontent.com/223020/216925340-582e7f5a-e99d-4701-b43c-530ceb79aeda.jpeg)

**Comment by leearmstrong** [comment]
I think this was fixed in 1.1 (8)

**Comment by inspirit** [comment]
hmm i'm pretty sure i've updated to the latest version because i saw in TestFlight notification with 2 new versions

**Comment by inspirit** [comment]
hmm looks like its indeed has been fixed already. uninstalled the app and installed it again and now its correctly rendered.
need some version info in the app :) i saw such issue here alredy

**Comment by jverkoey** [comment]
Yep that was a bug in that build that I didn't catch while testing and is now fixed. I'm going to put some focus on getting some test infra in place before the next build so that I can hopefully catch these regressions before publishing a build.
