### ISSUE TITLE
Watch complication is not updating

### ISSUE THREAD

**Issue by inspirit** [jverkoey/ElectricSidecar#54]
Hi! I've installed latest version and it seems that watch complication always show 100%. When clicking inside the app all info is correct there

**Comment by jverkoey** [comment]
In TestFlight, can you check which specific build version you're using and share it here? Also which Apple Watch are you using? Specifically the model and size.

**Comment by inspirit** [comment]
I have 1.1(12) installed, i tried remove and clean install also.
I have Apple watch Ultra

**Comment by inspirit** [comment]
Hi! after updating to 1.1(13) still have the same issue unfortunately

**Comment by inspirit** [comment]
after updating to watch os 9.4 and re-setting complication via watch app on the phone it draws charging status correctly now.
